name: BackstopJS

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'BackstopJS command to run'
        required: true
      filter:
        description: 'filter'
        required: false

jobs:
  BackstopJS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: andstor/backstopjs-action@master
        id: backstopjs
        env:
          BB_USERNAME: ${{ secrets.BB_USERNAME }}
          BB_PASSWORD: ${{ secrets.BB_PASSWORD }}
        with:
          command: ${{ github.event.inputs.command }}
          filter: ${{ github.event.inputs.filter }}

      - run: |
          git add ./${{steps.backstopjs.outputs.backstopjs-dir}}/bitmaps_reference/
          git commit -m "Update reference bitmaps"
          git push

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{steps.backstopjs.outputs.backstopjs-dir}}
          force_orphan: true

