name: BackstopJS

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'BackstopJS command to run'
        required: true
      filter:
        description: 'filter'
        required: false

jobs:
  BackstopJS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: andstor/wiki-watch
          path: previous-tests
          ref: gh-pages

      - run: |
          cp -rf ./previous-tests/bitmaps_test/ ./backstop_data/bitmaps_test/
      
      - uses: andstor/backstopjs-action@master
        id: backstopjs
        env:
          BB_USERNAME: ${{ secrets.BB_USERNAME }}
          BB_PASSWORD: ${{ secrets.BB_PASSWORD }}
        with:
          command: ${{ github.event.inputs.command }}
          filter: ${{ github.event.inputs.filter }}
          config_file: ./backstop.config.js

      - run: |
          cp -rf ./compare-app/build/ ./${{steps.backstopjs.outputs.backstopjs-dir}}/html_report
          node ./scripts/report.js
          cp -rf ./config.js ./${{steps.backstopjs.outputs.backstopjs-dir}}/html_report/config.js

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./${{steps.backstopjs.outputs.backstopjs-dir}}/bitmaps_reference/
          git commit -m "Update reference bitmaps"
          git push

      - name: Deploy
        if: ${{ success() || failure() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{steps.backstopjs.outputs.backstopjs-dir}}
          force_orphan: true

