name: BackstopJS

on:
  push:
    branches:
      - 'master'

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: andstor/backstopjs-action@master
        id: backstopjs
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        with:
          command: test
      - name: Deploy
        
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{steps.backstopjs.outputs.backstopjs-dir}}
          force_orphan: true

